server {
    listen 80;
    server_name _;

    root /usr/share/nginx/html;
    index index.html;

    location /figures/ {
        proxy_pass http://host.docker.internal:8000/figures/;
    }

    location / {
        try_files $uri $uri/ /index.html;
    }
}